version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./nextcloud-db:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    image: nextcloud
    ports:
      - ${PROXY_PORT}:80
    links:
      - db
    volumes:
      - ./nextcloud-file:/var/www/html
    restart: always
    env_file:
      - .env
